-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.1
    hooks:
    -   id: trailing-whitespace
        language_version: python3.6
    -   id: end-of-file-fixer
        language_version: python3.6
    -   id: autopep8-wrapper
        language_version: python3.6
        args:
        - -i
        - --ignore=E501
    -   id: check-docstring-first
        language_version: python3.6
    -   id: check-json
        language_version: python3.6
    -   id: pretty-format-json
        language_version: python3.6
        args:
        - --autofix
    -   id: check-added-large-files
        language_version: python3.6
    -   id: check-yaml
        language_version: python3.6
    -   id: debug-statements
        language_version: python3.6
    -   id: requirements-txt-fixer
        language_version: python3.6
    -   id: double-quote-string-fixer
        language_version: python3.6
    -   id: check-merge-conflict
        language_version: python3.6
    -   id: check-ast
        language_version: python3.6
    -   id: flake8
        language_version: python3.6
        args:
        - '-'
        - --ignore=E501,E402,F405
-   repo: https://github.com/pre-commit/pre-commit
    sha: v0.15.4
    hooks:
    -   id: validate_config
    -   id: validate_manifest
-   repo: https://github.com/asottile/reorder_python_imports
    sha: v0.3.5
    hooks:
    -   id: reorder-python-imports
        language_version: python3.6
-   repo: https://github.com/pre-commit/mirrors-autopep8
    sha: v1.3.2
    hooks:
    -   id: autopep8
        language_version: python3.6
